name: web app workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  webapptests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./web-app
    timeout-minutes: 6
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.10']

    steps:
      - name: check out repo code
        uses: actions/checkout@v3
      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-flask
      - name: execute unit tests
        run: pytest
